format_strings = true
imports_granularity = "Module"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
